USE [master]
GO

/****** Object:  Database [TcDataContext]    Script Date: 1/31/2024 6:17:43 PM ******/
CREATE DATABASE [TcDataContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TcDataContext', FILENAME = N'C:\TcDataContext.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TcDataContext_log', FILENAME = N'C:\TcDataContext_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TcDataContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TcDataContext] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TcDataContext] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TcDataContext] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TcDataContext] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TcDataContext] SET ARITHABORT OFF 
GO

ALTER DATABASE [TcDataContext] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TcDataContext] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TcDataContext] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TcDataContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TcDataContext] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TcDataContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TcDataContext] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TcDataContext] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TcDataContext] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TcDataContext] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TcDataContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TcDataContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TcDataContext] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TcDataContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TcDataContext] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TcDataContext] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TcDataContext] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TcDataContext] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TcDataContext] SET  MULTI_USER 
GO

ALTER DATABASE [TcDataContext] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TcDataContext] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TcDataContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TcDataContext] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TcDataContext] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TcDataContext] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TcDataContext] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TcDataContext] SET  READ_WRITE 
GO

